GO
/****** FHQQ313596790 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE GD_GONGDAN (
 		GONGDAN_ID  nvarchar(100) NOT NULL,
		TITLE nvarchar(100) DEFAULT NULL,
		CREATETIME nvarchar(32) DEFAULT NULL,
PRIMARY KEY CLUSTERED 
(
	[GONGDAN_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
